{"uuid": "8b89d84c-85c8-4af0-9b2d-df0873e66957", "children": ["5210e550-88b8-4d4d-80ac-14969df6b97d"], "befores": [{"name": "goods_cat", "status": "broken", "statusDetails": {"message": "requests.exceptions.ProxyError: HTTPSConnectionPool(host='newecshop.longtest.cn', port=443): Max retries exceeded with url: /admin/privilege.php (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))\n", "trace": "  File \"D:\\api-pythonproject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\api-pythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\api-pythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\api-pythonproject\\testcases\\conftest.py\", line 17, in goods_cat\n    return GoodsCatApi(base_url).login(*user)\n  File \"D:\\api-pythonproject\\apis\\base_api.py\", line 20, in login\n    self.session.post(url, data=payload)\n  File \"D:\\api-pythonproject\\venv\\lib\\site-packages\\requests\\sessions.py\", line 635, in post\n    return self.request(\"POST\", url, data=data, json=json, **kwargs)\n  File \"D:\\api-pythonproject\\venv\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"D:\\api-pythonproject\\venv\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"D:\\api-pythonproject\\venv\\lib\\site-packages\\requests\\adapters.py\", line 559, in send\n    raise ProxyError(e, request=request)\n"}, "start": 1678783823131, "stop": 1678783823144}], "start": 1678783823131, "stop": 1678783823281}