{"name": "test_get_goods_caat_with_csv", "status": "broken", "statusDetails": {"message": "ValueError: I/O operation on closed file.", "trace": "goods_cat = <apis.goods_cat_api.GoodsCatApi object at 0x04A8A550>\n\n    def test_get_goods_caat_with_csv(goods_cat):\n        data = load_csv('D:/api-pythonproject/data/goods_cat.csv')\n>       for line in data:\n\ntest_goods_cat.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\86157\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\csv.py:111: in __next__\n    self.fieldnames\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <csv.DictReader object at 0x04A8AB10>\n\n    @property\n    def fieldnames(self):\n        if self._fieldnames is None:\n            try:\n>               self._fieldnames = next(self.reader)\nE               ValueError: I/O operation on closed file.\n\nC:\\Users\\86157\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\csv.py:98: ValueError"}, "attachments": [{"name": "log", "source": "97243400-9bf4-4ad7-9f9f-3f6d96e4c1f6-attachment.txt", "type": "text/plain"}], "start": 1678186660767, "stop": 1678186660767, "uuid": "a983e953-3e50-496f-8ab0-c96d42afc880", "historyId": "00318afa04838eb2425be3b204525632", "testCaseId": "355e81767857c9c0e4b4b738c2c6e542", "fullName": "testcases.test_goods_cat#test_get_goods_caat_with_csv", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_goods_cat"}, {"name": "host", "value": "DESKTOP-A7I9MKJ"}, {"name": "thread", "value": "6712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_goods_cat"}]}